### PR TITLE
Reduced processing time for PDHG-TV and PDHG -TGV for the multichannel colour notebook 

### LINKED ISSUE #185: Colour Processing notebook takes too long to run
One of the PDHG cells takes 20mins. I wonder if we can reduce the number of iterations

### LINKED ISSUE #198: Error with font not found in Colour Processing Notebook - Windows 11 and New Training Platform (linux)
When I tried to run on my windows machine I couldn't run the Colour Processing notebook.

In the notebook text is added to an image, and to do this a font is specified.
`
font = ImageFont.truetype('DejaVuSerif.ttf', 50)`

The font doesn't exist on my windows machine so this fails with error:
`ImageFont.truetype cannot open resource`

We need to replace the font with something that is standard on all OS.

To get the notebook working on my windows machine I used:

`font = ImageFont.truetype('arial.ttf', 50)`

Need to test if this works on linux / find out if there is a standard font to use

### PR DESCRIPTION
**Pull request by MargaretDuff**

### CODE REVIEW

**Comment by MargaretDuff** [comment]
Closes #185

**Review by lauramurgatroyd — APPROVED** [review]
Great improvement, much faster and still looks well denoised :smile:

But please clear output before merging!

**Comment by MargaretDuff** [comment]
Closes #198: I added some instructions for windows. @lauramurgatroyd - please can you have a look?

**Review by lauramurgatroyd — APPROVED** [review]
It works!

**Comment by lauramurgatroyd** [comment]
Please add yourself to authors before merging

**Pull request merged**
