### PR TITLE
Gcolab

### PR DESCRIPTION
**Pull request by epapoutsellis**
[CIL on Colab](https://github.com/epapoutsellis/CIL-Demos/tree/gcolab/gcolab)

1.  CIL-Colab notebook.
2. Instructions in the readme.

After merging it we can add a Google Colab badge similar to Binder in the CIL-README.

### CODE REVIEW

**Review by jakobsj — COMMENTED** [review]
Looks good to me. Only thing, let us change the folder name to just colab, as gcolab is not a known name.

**Comment by gfardell** [comment]
I don't think we want the rendered notebook in the repo. Can you install nbstripout and run it first?
```
from cil.plugins.astra.operators import ProjectionOperator
from cil.plugins.astra.processors import FBP
```
should be 
```
from cil.plugins.astra import ProjectionOperator, FBP
```
as we expose them at a higher level. Once the notebook it striped I should be able to review properly and mark lines.

**Comment by jakobsj** [comment]
Could we progress this one please? @epapoutsellis if you can address Gemma's comments and let us know when ready for a last look? I've had use for CIL on colab recently and will have more uses coming up soon, so would be nice to get this demo available.

**Comment by epapoutsellis** [comment]
@jakobsj , @gfardell, output is cleared and fix the imports

**Comment by epapoutsellis** [comment]
I updated the colab notebook with TIGRE (optional) + Astra and `cil=23.0.1`.

**Review by jakobsj — CHANGES_REQUESTED** [review]
Hi @epapoutsellis , I have taken a look and run the notebook on colab. Overall I find that it runs fine and nicely demonstrates how one can use CIL on Colab.  A couple of points that need addressing:

1. Using ASTRA runs fine.  But installing TIGRE fails with this error:

```
Cloning into 'TIGRE'...
remote: Enumerating objects: 11462, done.
remote: Counting objects: 100% (71/71), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 11462 (delta 31), reused 28 (delta 7), pack-reused 11391
Receiving objects: 100% (11462/11462), 156.92 MiB | 30.61 MiB/s, done.
Resolving deltas: 100% (8442/8442), done.
/content/TIGRE/Python/TIGRE/Python
Traceback (most recent call last):
  File "/content/TIGRE/Python/TIGRE/Python/setup.py", line 11, in <module>
    from Cython.Distutils import build_ext
ModuleNotFoundError: No module named 'Cython'
Traceback (most recent call last):
  File "/content/TIGRE/Python/TIGRE/Python/example.py", line 5, in <module>
    import tigre
  File "/content/TIGRE/Python/TIGRE/Python/tigre/__init__.py", line 23, in <module>
    from .utilities.Ax import Ax
  File "/content/TIGRE/Python/TIGRE/Python/tigre/utilities/Ax.py", line 4, in <module>
    from _Ax import _Ax_ext
ModuleNotFoundError: No module named '_Ax'
```
2. Please emphasize even more that installing TIGRE is OPTIONAL and that the notebook can be run with ASTRA, in which case one SHOULD NOT run the TIGRE installation. Should also mention that to run with TIGRE, one needs to change to import ProjectionOperator and FBP from TIGRE instead of ASTRA.
3. Installalation of CIL using mamba: ccpi-regulariser is not used and should be omitted.
4. When setting up the ag and ig geometries, it would be nice if you illustrate them using show_geometry.
5. The projection operator uses GPU, but FBP uses CPU, why? I suggest to make both use GPU.
6. THe current problem is a small 2D problem for which GPU is not so critical. I think we have some 3D cone beam data sets that require GPU. Would it be worth making just a FDK recon of one of these to demonstrate there is enough power to do 3D conebeam?
7. The TV example is nice. But the progress printing is a bit confusing, since it shows some negative primal-dual gaps, here's the output:
```
     Iter   Max Iter     Time/Iter        Primal          Dual     Primal-Dual
                               [s]     Objective     Objective             Gap
        0        200         0.000    1.03436e+06  -0.00000e+00    1.03436e+06
       50        200         0.019    8.47112e+03   6.74937e+03    1.72175e+03
      100        200         0.016    7.65216e+03   7.73330e+03   -8.11419e+01
      150        200         0.015    7.56273e+03   7.51387e+03    4.88622e+01
      200        200         0.015    7.54320e+03   7.55865e+03   -1.54492e+01
----------------------------------------------------------------------------
      200        200         0.015    7.54320e+03   7.55865e+03   -1.54492e+01
```
Could you adjust the example a bit so that the progress printing is simpler?

So, these are just points that will make it slightly clearer along the way, overall the notebook achieves its aim of demonstrating CIL on colab very nicely, and so I look forward to getting this merged. Also very nice to have the button to directly open CIL on Colab.

**Comment by epapoutsellis** [comment]
Thank you @jakobsj  for the review. I will try to address all of your points and get back to you asap.

**Comment by epapoutsellis** [comment]
Hi @jakobsj , I have update the gcolab notebook.

It is tested with Python 3.9 (supported python version until mid may) and current Python 3.10, for both the Astra and TIGRE backends.

- It uses the Steelwire dataset for limited angle tomography application.
- Presents `show_geometry` utility.
- Presents `TransmissionAbsorptionConverter`, `Slicer`, `CentreOfRotationCorrector` processors.
- Runs `FBP` reconstruction
- Solves TV recon problem using the `PDHG` algorithm (implicit) with `FGP_TV` (device="gpu").

1.-2. If you want to use TIGRE, you need to install TIGRE **first** and the astra from mamba. I have added instructions in the nb.
3. Added the ccpi-regtk, to showcase tv regularisation with gpu.
4. Added `show_geometry`
5. Fixed. Added also instructions if TIGRE backend is used.
6. Steelwire is used (3D Parallel). We can add the Lizard dataset (Cone geometry). The problem is that the user need to download the dataset (`wget`). This is a small dataset, sometimes it takes secs to download and sometimes minutes. Not sure why... Also, we have to include some additional functions to preprocess this dataset.
7. Fixed. Only primal objective is printed. Please note when gpu projectors are used, there is a problem with the dual gap due to the operator mismatch.

**Review by jakobsj — CHANGES_REQUESTED** [review]
I have tested this and was able to run the complete notebook with the 3.10 version and astra.  The notebook explains the current difficulties and workarounds in the beginning, which is necessary and helpful, but it does make the notebook a bit heavy and technical to start out with.  I don't mind keeping it like this for now though. In some places some more guidance could be given, for example it was not immediately clear that grey boxes with the code to be run had been added as markdown copies, in addition to the code boxes themselves. But again, this is okay for now.  The only thing I would ask, is if a colab button could be added in the readme in the top directory, next to the binder one, so that users immediately see both binder and colab options next to each other, in addition to the current colab button in the readme inside the colab folder.

**Comment by jakobsj** [comment]
Maybe someone else can try it out as well and provide another review so that we can get this merged Thursday? @gfardell @paskino @lauramurgatroyd

**Comment by epapoutsellis** [comment]
Hi @jakobsj , I totally agree with your comments. It's complicated but at least for now is stable for both python 3.9, 3.10 versions.

Certainly, it can be improved using pip for instance. This is the preferred way for gcolab. The alternative is to use condacolab. But we need to have package installers for cil, tomophantom, astra-toolbox, ccpiregtk etc. Also, since gcolab does not like conda environments, we need to change our default installation step.

I have added a gcolab buttome next to binder.

**Review by jakobsj — APPROVED** [review]

**Comment by jakobsj** [comment]
@epapoutsellis do you have time to look at resolving the conflicts, so we can get it merged today?

**Pull request merged**
