### PR TITLE
Exercise 3

### PR DESCRIPTION
**Pull request by gfardell**
Draft pull request with the rendered notebook for ease of comments.

Once we are happy with the structure and scope I will create the snippets and remove the output before we merge.

 - [x] Add snippets
 - [x] Update filepath for the cloud
 - [x] Test on cloud 23.0
 - [x] Remove output

### CODE REVIEW

**Comment by jakobsj** [comment]
Looks good to me.  No need to add further material, it's quite complete and comprehensive as is.

**Review by lauramurgatroyd — APPROVED** [review]
Hi,

Please see my PR with minor text changes and link to dataset on jupyterhub,

I wonder if we should:
- add instructions to show them how they can find the xtekct file to have a look at on the jupyterhub
- in the common mistakes section near the end, state that the Cone2D method expects the distances between source and detector etc. to be along the y axis

**Comment by gfardell** [comment]
Made changes.  If everyone is happy I'll strip the output and then merge.

**Review by lauramurgatroyd — APPROVED** [review]
It's looking great!

**Pull request merged**
