### PR TITLE
Remove unused var and relax alpha check in iterative notebooks

### LINKED ISSUE #117: Notebook 1 week 2 too hard check?
We use the following hard statement:

```python
if myFISTATV.g.alpha == 0.02 and myFISTATV.iteration > 199:
   print("Good job, carry on!")
else:
    raise ValueError("Try again: run 200 iterations with alpha of 0.02")
```

which could be substituted with 

```python
import numpy as np
if np.testing.assert_almost_equal(myFISTATV.g.alpha, 0.02, decimal=2) and myFISTATV.iteration > 199:
    print("Good job, carry on!")
else:
    raise ValueError("Try again: run 200 iterations with alpha of 0.02")
```

### LINKED ISSUE #141: 04_FBP_CGLS_SIRT contains unused variable
Cell [21] which adds noise contains a variable which is never used:

```python
# Incident intensity: lower counts will increase the noise
background_counts = 20000 

# Convert the simulated absorption sinogram to transmission values using Lambert-Beer. 
# Use as mean for Poisson data generation.
# Convert back to absorption sinogram.
counts = background_counts * np.exp(-sino.as_array())
tmp = np.exp(-sino.as_array())
noisy_counts = np.random.poisson(counts)
nonzero = noisy_counts > 0
sino_out = np.zeros_like(sino.as_array())
sino_out[nonzero] = -np.log(noisy_counts[nonzero] / background_counts)

# allocate sino_noisy and fill with noisy data
sino_noisy = ag.allocate()
sino_noisy.fill(sino_out)
```

The `tmp` variable is never used

### PR DESCRIPTION
**Pull request by lauramurgatroyd**
Closes #117 
Closes #141 
Closes part of https://github.com/TomographicImaging/CIL-Demos/issues/196

### CODE REVIEW

**Comment by MargaretDuff** [comment]
Thanks @lauramurgatroyd . In the 01_optimisation... notebook, when we test before letting people carry on we check that the user has run 200 iterations:
image.
But the default is 50: 
image
and we don't tell people to change the number of iterations: 
image.

I suggest changing the number of iterations run to 200

**Comment by MargaretDuff** [comment]
In the 01_optimisation notebook, can we add a sentence after the plot of the converged PDHG solution, something like "We can now see the resulting image matches that of the FISTA solution."

At the end of here maybe :)
image

**Comment by lauramurgatroyd** [comment]
Thanks, have updated

**Review by MargaretDuff — APPROVED** [review]
Looks good - Thanks @lauramurgatroyd!

**Pull request merged**
