### PR TITLE
fix default sigma/tau, close #74

### LINKED ISSUE #74: Default sigma, tau values in Week2_03_PDHG
Default values of sigma, tau  = 1/K.norm() and we need to update the text (markdown)

### PR DESCRIPTION
**Pull request by epapoutsellis**
See https://nbviewer.org/github/TomographicImaging/CIL-Demos/blob/fix_default_sigma_tau_values/training/2021_Fully3D/Week2/03_PDHG.ipynb

`nbstripout` before accepting merge.

### CODE REVIEW

**Comment by lauramurgatroyd** [comment]
would you like me to run nbstripout and then push to this branch?

**Comment by epapoutsellis** [comment]
If you are ok with the changes, yes. and merge in master

**Comment by lauramurgatroyd** [comment]
Once I ran the stripout I realised I was definitely not qualified to check this!

**Comment by lauramurgatroyd** [comment]
However, I am happy with the fix to the number of angles that closes #71

**Pull request merged**
